Seongil-Yoon/iMint

src/main/java/multi/fclass/iMint/mypage/dao/IMypageDAO.java
src/main/java/multi/fclass/iMint/mypage/dto/WishListDTO.java
src/main/java/multi/fclass/iMint/mypage/service/IMypageService.java
src/main/java/multi/fclass/iMint/mypage/service/MypageServiceImpl.java
src/main/resources/mybatis/mappers/mypage-mapper.xml

현재 예약중(구매자) 목록은 제외하고 관심 목록만 출력 가능

관심 목록 조회 서비스 구현

---

src/main/java/multi/fclass/iMint/mypage/service/MypageServiceImpl.java
src/main/resources/mybatis/mappers/mypage-mapper.xml

관심/구매예약목록 조회 서비스 구현

---

src/main/java/multi/fclass/iMint/mypage/dto/MypageDTO.java

DTO에 롬복 적용

---

src/main/java/multi/fclass/iMint/wishlist/dao/IWishlistDAO.java
src/main/java/multi/fclass/iMint/wishlist/dto/WishlistDTO.java
src/main/java/multi/fclass/iMint/wishlist/service/IWishlistService.java
src/main/java/multi/fclass/iMint/wishlist/service/WishlistServiceImpl.java
src/main/resources/mybatis/mappers/wishlist-mapper.xml
src/main/resources/mybatis/mybatis-config.xml

상품별 관심등록수, 사용자의 상품관심등록여부 확인, 관심등록, 관심해제 서비스 작성
RestController 작성 예정

관심목록 관련 서비스 구현

---

src/main/java/multi/fclass/iMint/mypage/dao/IMypageDAO.java
src/main/java/multi/fclass/iMint/mypage/service/MypageServiceImpl.java
src/main/resources/mybatis/mappers/mypage-mapper.xml

마이페이지 관련 서비스 수정

---

src/main/java/multi/fclass/iMint/security/auth/config/OAuthAttributes.java
src/main/java/multi/fclass/iMint/security/auth/config/SecurityConfig.java
src/main/java/multi/fclass/iMint/security/controller/IndexController.java
src/main/java/multi/fclass/iMint/security/dao/IUserDAO.java
src/main/java/multi/fclass/iMint/security/model/Role.java
src/main/java/multi/fclass/iMint/security/model/SessionUser.java
src/main/java/multi/fclass/iMint/security/model/User.java
src/main/java/multi/fclass/iMint/security/service/CustomOAuth2UserService.java
src/main/resources/mybatis/mappers/security-mapper.xml
src/main/webapp/WEB-INF/views/member/register.jsp

SNS가입 후 나이 받아와서 보호자, 아이를 연령대로 구분하는 로직완성하였습니다.
회원가입은 총 4단계인데 추후 보호자 내 동네 설정, 아이 보호자 연결만 추가되면 회원가입 로직이 완료됩니다.

회원가입 전체 로직(보호자: 내 동네 설정 API, 아이: 보호자 연결 추후 추가 예정)

---

src/main/java/multi/fclass/iMint/wishlist/controller/WishlistController.java
src/main/java/multi/fclass/iMint/wishlist/dao/IWishlistDAO.java
src/main/java/multi/fclass/iMint/wishlist/service/IWishlistService.java
src/main/java/multi/fclass/iMint/wishlist/service/WishlistServiceImpl.java
src/main/resources/mybatis/mappers/wishlist-mapper.xml

관심목록 관련 서비스 추가 구현

---

src/main/java/multi/fclass/iMint/mypage/dao/IMypageDAO.java
src/main/java/multi/fclass/iMint/mypage/service/IMypageService.java
src/main/java/multi/fclass/iMint/mypage/service/MypageServiceImpl.java
src/main/resources/mybatis/mappers/mypage-mapper.xml

관심목록과의 명칭구별을 위해 메소드 명칭 getWishList -> getWishAndReserveList 변경
매개변수 Map -> 각각 입력으로 변경

마이페이지 관련 기능 수정

---

src/main/java/multi/fclass/iMint/mypage/dao/IMypageDAO.java
src/main/java/multi/fclass/iMint/mypage/dto/MypageChatroomDTO.java
src/main/java/multi/fclass/iMint/mypage/service/IMypageService.java
src/main/java/multi/fclass/iMint/mypage/service/MypageServiceImpl.java
src/main/resources/mybatis/mappers/mypage-mapper.xml
src/main/resources/mybatis/mybatis-config.xml

채팅방 목록 조회 서비스 임시 구현

---

src/main/java/multi/fclass/iMint/mypage/controller/MypageCotroller.java
src/main/java/multi/fclass/iMint/mypage/dao/IMypageDAO.java
src/main/java/multi/fclass/iMint/mypage/dto/MypageChildDTO.java
src/main/java/multi/fclass/iMint/mypage/dto/MypageDTO.java
src/main/java/multi/fclass/iMint/mypage/service/IMypageService.java
src/main/java/multi/fclass/iMint/mypage/service/MypageServiceImpl.java
src/main/resources/mybatis/mappers/mypage-mapper.xml
src/main/resources/mybatis/mybatis-config.xml
src/main/webapp/WEB-INF/views/member/guard-mypage/guard-mylist.jsp
src/main/webapp/WEB-INF/views/member/guard-mypage/mylist-content-complete.jsp
src/main/webapp/WEB-INF/views/member/guard-mypage/mylist-content-selling.jsp
src/main/webapp/WEB-INF/views/member/guard-mypage/mylist-content-wish-buy.jsp

1. 내 아이의 id와 nick을 담는 MypageChildDTO 생성
2. 내 아이의 id와 nick 목록을 가져오는 getMyChildrenList() 서비스 생성
3. 뷰에 전달하는 객체를 key로 childNick, value로 List<MypageDTO>를 가지는 Map으로 변경

내 아이 목록 Map으로 구현

---

src/main/java/multi/fclass/iMint/wishlist/dao/IWishlistDAO.java
src/main/java/multi/fclass/iMint/wishlist/service/WishlistServiceImpl.java
src/main/resources/mybatis/mappers/wishlist-mapper.xml

조건 판단 오류 수정

---

src/main/java/multi/fclass/iMint/security/auth/config/SecurityConfig.java

.denyAll() => .authenticated();

로그인후 403문제 해결

---

src/main/java/multi/fclass/iMint/wishlist/controller/WishlistController.java
src/main/resources/static/js/goods/goods-detail.js

데이터를 가져오는 동작은 GET, 그 외의 동작은 POST로 할당했습니다

관심목록 관련 HTTP 메소드 수정

---

src/main/java/multi/fclass/iMint/transaction/dto/TransactionChatroomDTO.java
src/main/resources/mybatis/mappers/transaction-mapper.xml
src/main/resources/static/js/chat/chatbox.js
src/main/webapp/WEB-INF/views/transaction/resrv.jsp
src/main/webapp/WEB-INF/views/transaction/trx.jsp

판매완료 버튼 동작 임시 구현

---

src/main/java/multi/fclass/iMint/MyWebConfig.java
src/main/java/multi/fclass/iMint/security/auth/config/SecurityConfig.java

.antMatchers("/iMintImage/**").permitAll()

SecurityConfig, MyWebConfig 수정

---

src/main/resources/static/js/chat/chatbox.js
src/main/webapp/WEB-INF/views/include/header.jsp

GUARD나 CHILD가 아닐 때에는 웹소켓에 접속을 시도하지 않도록 수정했습니다

스크롤 맨 위에서 이전 메세지(페이지) 로딩 구현

---

src/main/java/multi/fclass/iMint/goods/controller/GoodsController.java
src/main/java/multi/fclass/iMint/goods/service/GoodsServiceImpl.java
src/main/java/multi/fclass/iMint/member/service/MemberServiceImpl.java
src/main/resources/static/css/goods/carousel.css
src/main/resources/static/css/goods/goods-detail.css
src/main/resources/static/css/goods/goods-write.css
src/main/resources/static/css/main.css
src/main/resources/static/js/goods/goods-modify.js
src/main/resources/static/js/goods/goods-write.js
src/main/resources/static/js/header-search.js
src/main/resources/static/js/main.js
src/main/webapp/WEB-INF/views/goods/goods-modify.jsp
src/main/webapp/WEB-INF/views/goods/goods-write.jsp
src/main/webapp/WEB-INF/views/include/header.jsp

상품상세,수정,등록, 메인, 음성인식 세부디자인 변경

---

src/main/resources/mybatis/mappers/mypage-mapper.xml
src/main/resources/static/js/chat/chatbox.js

채팅방 목록을 가져오는 SQL의 오류 수정
채팅방 거래 관련 알림에 sweetalert 사용

채팅방 목록 표시 오류 수정, 채팅방 거래 관련 알림 수정

---

src/main/resources/static/css/chat/chatbox.css

메세지에서 테두리 제거
프로필 이미지, 상품 이미지, 거래 상태, 가격제안 허용여부, 메세지에 그림자 적용

일부 상자형 요소에서 테두리 제거 및 그림자 적용

---

src/main/resources/templates/goods/goods-modify.html
src/main/resources/templates/goods/goods-write.html

goods-libs replace 경로 수정
name 속성이 중복 등장하는 부분 수정

상품 등록/수정 페이지 오류 수정

---

src/main/resources/templates/goods/goods-detail.html
src/main/resources/templates/goods/goods-modify.html
src/main/resources/templates/goods/goods-write.html

safe navigationasafe navigation이라고 해서 null일 때 에러 대신 null을 반환합니다

타임리프 ?. 참조변경

---

src/main/java/multi/fclass/iMint/block/controller/BlockCotroller.java

MemberDTO를 Autowired로 선언해서 발생하는 오류 해결을 위해 해당 구문 삭제했습니다

@Autowired MemberDTO 제거

---

src/main/java/multi/fclass/iMint/block/dao/IBlockDAO.java
src/main/java/multi/fclass/iMint/block/service/BlockServiceImpl.java
src/main/java/multi/fclass/iMint/block/service/IBlockService.java
src/main/resources/mybatis/mappers/block-mapper.xml

1. 보호자의 경우: 본인이 차단한 회원목록 조회
2. 아이의 경우: 본인+보호자가 차단한 회원목록 조회

차단목록 조회 서비스 추가

---

src/main/java/multi/fclass/iMint/mypage/controller/MypageCotroller.java
src/main/java/multi/fclass/iMint/mypage/service/MypageServiceImpl.java

내용 없는 채팅방을 마이페이지 컨트롤러에서만 제거하도록 수정

---

src/main/java/multi/fclass/iMint/mail/dto/MailDTO.java
src/main/java/multi/fclass/iMint/mail/service/IMailService.java
src/main/java/multi/fclass/iMint/mail/service/MailServiceImpl.java
src/main/java/multi/fclass/iMint/notification/service/NotificationServiceImpl.java
src/test/java/multi/fclass/iMint/notification/service/NotificationServiceImplTest.java

거래메일알림 정보추가

---

src/main/java/multi/fclass/iMint/chat/controller/ChatController.java
src/main/java/multi/fclass/iMint/chat/dao/IChatDAO.java
src/main/java/multi/fclass/iMint/chat/service/ChatServiceImpl.java
src/main/java/multi/fclass/iMint/notification/service/NotificationServiceImpl.java
src/main/resources/mybatis/mappers/chat-mapper.xml
src/main/resources/static/js/chat/chatbox.js

1. 이미 열려있는 채팅방인 경우: unread 클래스 추가하고 마지막 메세지를 새 메세지 내용으로 변경
2. 새로 열린 채팅방인 경우: 채팅방 목록 다시 불러오기

채팅방 목록을 보고 있는 동안에도 새 메세지 갱신
